apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-ilycfsfj
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-ilycfsfj:df455a59aae4cdb2a82f3b22f898564c3df0bf08@sha256:75c0d7da389c2ee5231713dad45bc31b94f350c00a00725af3184c4d415f734d
        name: container-image  
