apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ilycfsfj
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-ilycfsfj:5148a2e4deea5d868c973afaa34c730c65cd9a9c@sha256:83393a8b1eefd5a5fdab5207a7f1559f6904f928cc3f8a856b2dfd73499ed1a0
          name: container-image
